# Generated by Django 2.2.4 on 2019-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alanlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.CharField(max_length=50)),
                ('a2', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
