# Generated by Django 2.2.4 on 2019-11-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20191121_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alanlar',
            old_name='a1',
            new_name='adını_yaz',
        ),
        migrations.RenameField(
            model_name='alanlar',
            old_name='a2',
            new_name='farketmez',
        ),
        migrations.RenameField(
            model_name='alanlar',
            old_name='a3',
            new_name='isaretle',
        ),
        migrations.RenameField(
            model_name='alanlar',
            old_name='a4',
            new_name='isaretleme',
        ),
    ]
