# Generated by Django 2.2.4 on 2019-11-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20191121_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alanlar',
            old_name='adını_yaz',
            new_name='adını_buraya_yaz',
        ),
    ]
